refresh_status:
  description: "Poll car for latest status (Takes up to 5mins to update once this function has been run!)"
clear_tokens:
  description: "Clear the cached tokens"
reload:
  name: Reload
  description: "Reload the Fordpass Integration"
poll_api:
  name: Poll API
  description: "Manually poll API for data update (Warning: doing this too often could result in a ban)"